### ISSUE TITLE
Is destructuring the only way to get [AjaxReq] for my api?

### ISSUE THREAD

**Issue by seanhess** [haskell-servant/servant-jquery#12]
In your example, you use `:<|>` to pull out your `AjaxReq` objects, then manually construct a list of the routes to generate JS for. 

Is there a function that will take an entire API and turn it into `[AjaxReq]`? For most apps the destructuring would get pretty cumbersome.

**Comment by alpmestan** [comment]
The thing is that most apps have a static file serving "endpoint" (i.e a `Raw` endpoint that uses `serveDirectory`), and usually we don't want to generate javascript functions to query these =)

If you want though I guess we could expose a function that builds a list of `AjaxReq`s or that directly hands you the whole generated javascript code as a `String`? Which would you prefer?

**Comment by seanhess** [comment]
I don't understand how servant works very well, but can you exclude raw endpoints like that when you output the list? I would probably use WAI middleware to server files anyway. The static files aren't really a part of my API, they're just something provided by the server. 

Either one of those options would work for me! Maybe both :)

**Comment by alpmestan** [comment]
Alright, something like:

``` haskell
class GenerateCode reqs where
  jsFor :: reqs -> String

instance GenerateCode AjaxReq where
  jsFor = generateJS

instance GenerateCode rest => GenerateCode (AjaxReq :<|> rest) where
  jsFor (req :<|> rest) = jsFor req ++ jsFor rest

jsForAPI :: (HasJQ api, GenerateCode (JQ api))
         => Proxy api -> String
jsForAPI p = jsFor (jquery p)
```

(sorry for the lack of inspiration for function/class names here...)

Any suggestion regarding the names of these guys? They probably will make it for the next release :)

**Comment by seanhess** [comment]
Works for me!
