### ISSUE TITLE
Overlapping names

### ISSUE THREAD

**Issue by seanhess** [haskell-servant/servant-jquery#13]
Servant is using the same name `getsources` for both `GET /sources` and `GET /sources/:id`. Is there some way it could figure out to call the second one `getsource`?

```
type Api = "sources" :> Get [Source] :<|> "sources" :> Capture "id" Text :> Get (Source)
```

**Comment by jkarni** [comment]
Great question. I'd suggest manually or automatically [0] changing the produced source code for now, but we'll keep this issue open and try to figure out a general way of preventing/resolving conflicting names.

[0] Something as simple as `sed  '0,/getsources(/! s/getsources(/getsourcesCapture(/' <file>` might work, even though it's pretty brittle.

**Comment by alpmestan** [comment]
Unless anyone has a suggestion for an algorithm that can automatically generate decent names from our various combinators + static strings?

**Comment by jkarni** [comment]
This issue was moved to haskell-servant/servant#38
