### ISSUE TITLE
Defining function rendering settings

### ISSUE THREAD

**Issue by rtrvrtg** [haskell-servant/servant-jquery#7]
I was wondering if there are any plans to change the way that servant-jquery's Javascript wrapper functions get rendered. Currently, they're all rendered like so:

```javascript
function getsomething(onSuccess, onError) {
```

However, I was wondering if we could customise the `generateJS` method to support alternative rendering methods, such as functions as variables, the Javascript Module Pattern, CommonJS (which is the same as the current one but with the addition of an `exports` declaration), and Purescript-ready methods (which require a bunch of nested functions, one for each parameter).

The outcome is that we might be able to invoke, say,

```haskell
generateJS' (ModulePatternOutput "Foo.MySubmodule") getSomethingAjaxReq
```

and get

```javascript
Foo.MySubmodule.getsomething = function(onSuccess, onError){
...
```

I'm happy to undertake investigation into this and put together a PR for it, but I was wondering what your thoughts were on this.

**Comment by alpmestan** [comment]
I wholeheartedly agree that this would be nice to have. The current implementation is the result of me putting together just what I needed at that time. We could definitely add an `Options` or `Settings` or `OutputFormat` type or something that would specify how we want the generated javascript to look like. I would just like however to keep the simple use case simple to write, so yeah we could have a `generateJS'` function next to the current one that supports fancy options, and have the current one be implemented in term of it using default settings to generate the same kind of JS code that we get now.

Does that sound good to you?

**Comment by rtrvrtg** [comment]
Sounds good to me. If we need to provide a default setting, we can set it to be the current, simple output method.

**Comment by alpmestan** [comment]
Perfect. Let me know if you need any help in working on this, although I don't have time to undertake this myself (alone) these days.

**Comment by alpmestan** [comment]
@christian-marie Do you guys still want this to happen or can we close this ticket?

**Comment by jkarni** [comment]
This issue was moved to haskell-servant/servant#39
